"""Shared Modulens SDK defaults and limits."""
from __future__ import annotations

CALL_STARTS_MAX = 10_000
DEFAULT_SAMPLE_RATE = 1.0
DEFAULT_FLUSH_INTERVAL_SEC = 120.0
FLUSH_THREAD_JOIN_TIMEOUT_SEC = 2

PROFILE_EXCEPTION_TUPLE_MIN_LEN = 3
PROFILE_EXCEPTION_TRACEBACK_INDEX = 2

DURATION_SEC_DECIMALS = 2
TOTAL_TIME_SEC_DECIMALS = 4
AVG_TIME_MS_DECIMALS = 2
MS_PER_SEC = 1000.0

DEFAULT_RUNTIME_REPORT_PATH = "modulens_output/runtime_report.json"
LOCAL_REPORT_JSON_INDENT = 2
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024
MAX_FILE_REPORTS = 500
FILE_REPORT_TRIM_DIVISOR = 2

INGEST_ENDPOINT = "/ingest"
MAX_HTTP_RETRIES = 2
HTTP_RETRY_DELAY_SEC = 1.0
HTTP_REQUEST_TIMEOUT_SEC = 30

VARIANT_KEY_LEN_DEFAULT = 128
VARIANT_KEY_LEN_MIN = 16
VARIANT_KEY_LEN_MAX = 512

DISTINCT_VARIANTS_DEFAULT = 64
DISTINCT_VARIANTS_MIN = 4
DISTINCT_VARIANTS_MAX = 256

VARIANT_KEY_TRUNCATE_ELLIPSIS_LEN = 3
OVERFLOW_VARIANT_KEY = "__other__"
VARIANT_NULL = "null"
VARIANT_TRUE = "true"
VARIANT_FALSE = "false"

DEFAULT_MODULENS_API_URL = "https://modulens-backend.onrender.com"
DEFAULT_ENVIRONMENT = "production"
DEFAULT_OUTPUT_MODE = "http"
DEFAULT_EXCLUDE_MODULES = ("flask", "werkzeug", "gunicorn", "logging")
