"""Shared Modulens SDK defaults and limits."""

# Profiler
CALL_STARTS_MAX = 10_000
DEFAULT_SAMPLE_RATE = 1.0
DEFAULT_FLUSH_INTERVAL_SEC = 120.0
FLUSH_THREAD_JOIN_TIMEOUT_SEC = 2

PROFILE_EXCEPTION_TUPLE_MIN_LEN = 3
PROFILE_EXCEPTION_TRACEBACK_INDEX = 2

DURATION_SEC_DECIMALS = 2
TOTAL_TIME_SEC_DECIMALS = 4
AVG_TIME_MS_DECIMALS = 2
MS_PER_SEC = 1000.0

# Local report file
DEFAULT_RUNTIME_REPORT_PATH = "modulens_output/runtime_report.json"
LOCAL_REPORT_JSON_INDENT = 2
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024
MAX_FILE_REPORTS = 500
FILE_REPORT_TRIM_DIVISOR = 2

# Ingest HTTP
INGEST_ENDPOINT = "/ingest"
MAX_HTTP_RETRIES = 2
HTTP_RETRY_DELAY_SEC = 1.0
HTTP_REQUEST_TIMEOUT_SEC = 30
HTTP_SUCCESS_STATUS_MIN = 200
HTTP_SUCCESS_STATUS_MAX_EXCLUSIVE = 300
HTTP_CLIENT_ERROR_MIN = 400
HTTP_CLIENT_ERROR_MAX_EXCLUSIVE = 500
HTTP_TOO_MANY_REQUESTS = 429

# Feature flags
MAX_VARIANT_KEY_LEN = 128
MAX_DISTINCT_VARIANTS_PER_FLAG = 64
MIN_VARIANT_KEY_LEN = 16
MAX_VARIANT_KEY_LEN_CAP = 512
MIN_DISTINCT_VARIANTS_PER_FLAG = 4
MAX_DISTINCT_VARIANTS_PER_FLAG_CAP = 256
VARIANT_KEY_TRUNCATE_ELLIPSIS_LEN = 3
OVERFLOW_VARIANT_KEY = "__other__"
VARIANT_NULL = "null"
VARIANT_TRUE = "true"
VARIANT_FALSE = "false"

# Config defaults
DEFAULT_MODULENS_API_URL = "https://modulens-backend.onrender.com"
DEFAULT_ENVIRONMENT = "production"
DEFAULT_OUTPUT_MODE = "http"
DEFAULT_EXCLUDE_MODULES = ("flask", "werkzeug", "gunicorn", "logging")
